# Generated by Django 5.2.6 on 2025-10-01 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Πακέτο')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Τιμή Πακέτου')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Υπηρεσία')),
                ('gender', models.CharField(choices=[('any', 'Οποιοδήποτε'), ('female', 'Γυναίκα'), ('male', 'Άνδρας')], default='any', max_length=10, verbose_name='Φύλο')),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Τιμή')),
                ('duration_min', models.PositiveIntegerField(default=30, verbose_name='Διάρκεια (λεπτά)')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Κατηγορία')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='clients.client')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.package')),
            ],
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions', models.PositiveIntegerField(default=1, verbose_name='Συνεδρίες')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.package')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.service')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_sessions', models.PositiveIntegerField(default=0)),
                ('client_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.clientpackage')),
                ('package_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.packageitem')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalog.servicecategory'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('category', 'name', 'gender')},
        ),
    ]
