# Generated by Django 5.2.6 on 2025-10-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Μηχάνημα')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργό')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Όνομα Δωματίου')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργό')),
            ],
        ),
    ]
