# Generated by Django 5.2.6 on 2025-10-01 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('catalog', '0001_initial'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=64, verbose_name='Περιοχή')),
                ('spot_size_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Spot size (mm)')),
                ('fluence_j_cm2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ενέργεια (J/cm²)')),
                ('pulse_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Παλμοί')),
                ('remarks', models.TextField(blank=True, verbose_name='Παρατηρήσεις')),
                ('charge_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Χρέωση')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Πληρωμή')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Μετρητά'), ('card', 'Κάρτα'), ('other', 'Άλλο')], max_length=16, verbose_name='Μέθοδος')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='appointments.appointment')),
                ('client_package_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='catalog.clientpackageitem', verbose_name='Συνεδρία από Πακέτο')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.machine')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
