# Generated by Django 5.2.6 on 2026-01-20 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('technician', 'Laser Technician'), ('nurse', 'Nurse'), ('doctor', 'Doctor'), ('receptionist', 'Receptionist'), ('manager', 'Manager'), ('other', 'Other')], default='technician', max_length=20, verbose_name='Position')),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract')], default='full_time', max_length=20, verbose_name='Employment Type')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Hire Date')),
                ('employee_id', models.CharField(blank=True, max_length=20, verbose_name='Employee ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name='Emergency Contact')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, verbose_name='Emergency Phone')),
                ('certifications', models.TextField(blank=True, help_text='List any relevant certifications', verbose_name='Certifications')),
                ('specializations', models.TextField(blank=True, verbose_name='Specializations')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='staff/avatars/', verbose_name='Avatar')),
                ('is_active_staff', models.BooleanField(default=True, verbose_name='Active Staff')),
                ('can_be_booked', models.BooleanField(default=True, help_text='Can clients book appointments with this staff member?', verbose_name='Can Be Booked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'ordering': ['user__name'],
            },
        ),
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('type', models.CharField(choices=[('vacation', 'Vacation'), ('sick', 'Sick Leave'), ('personal', 'Personal Day'), ('training', 'Training'), ('other', 'Other')], default='vacation', max_length=20, verbose_name='Type')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Approval Date')),
                ('approval_notes', models.TextField(blank=True, verbose_name='Approval Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_day_offs', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_offs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Day Off',
                'verbose_name_plural': 'Days Off',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['staff', 'start_date'], name='staff_dayof_staff_i_98a4f3_idx'), models.Index(fields=['start_date', 'end_date'], name='staff_dayof_start_d_4beb12_idx')],
            },
        ),
    ]
