# Generated by Django 5.2.6 on 2026-01-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='annual_leave_allowance',
            field=models.DecimalField(decimal_places=1, default=21.0, help_text='Total days of leave allowed per year', max_digits=5, verbose_name='Annual Leave Allowance (Days)'),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='type',
            field=models.CharField(choices=[('leave', 'Leave'), ('sick', 'Sick Leave'), ('half_day', 'Half Day'), ('other', 'Other')], default='leave', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(blank=True, help_text='e.g., Laser Technician, Senior Nurse, Receptionist', max_length=100, verbose_name='Position'),
        ),
    ]
