# Generated by Django 5.2.6 on 2026-01-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffprofile_annual_leave_allowance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoff',
            name='type',
            field=models.CharField(choices=[('leave', 'Leave'), ('sick', 'Sick Leave'), ('half_day', 'Half Day'), ('other', 'Other/Compensation')], default='leave', max_length=20, verbose_name='Type'),
        ),
    ]
