# Generated by Django 5.2.6 on 2026-01-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_dayoff_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='other_balance',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Accumulated compensation/bonus days (starts at 0, increases with Other entries)', max_digits=5, verbose_name='Other/Compensation Balance (Days)'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='sick_leave_allowance',
            field=models.DecimalField(decimal_places=1, default=10.0, help_text='Sick leave days allowed per year', max_digits=5, verbose_name='Sick Leave Allowance (Days)'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='annual_leave_allowance',
            field=models.DecimalField(decimal_places=1, default=21.0, help_text='Regular leave days allowed per year (includes half days)', max_digits=5, verbose_name='Annual Leave Allowance (Days)'),
        ),
    ]
