# Generated by Django 5.2.6 on 2026-03-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staffprofile_other_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='working_schedule',
            field=models.JSONField(blank=True, default=dict, help_text='Weekly working schedule with days and hours', verbose_name='Working Schedule'),
        ),
    ]
