# Generated by Django 5.2.6 on 2025-10-01 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Ονοματεπώνυμο')),
                ('phone', models.CharField(db_index=True, max_length=32, verbose_name='Τηλέφωνο')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Ημ/νία γέννησης')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('skin_type', models.CharField(blank=True, choices=[('I', 'Fitzpatrick I'), ('II', 'Fitzpatrick II'), ('III', 'Fitzpatrick III'), ('IV', 'Fitzpatrick IV'), ('V', 'Fitzpatrick V'), ('VI', 'Fitzpatrick VI')], max_length=3, null=True, verbose_name='Τύπος δέρματος')),
                ('hair_color', models.CharField(blank=True, choices=[('black', 'Μαύρο'), ('dark_brown', 'Σκούρο καστανό'), ('brown', 'Καστανό'), ('light_brown', 'Ανοιχτό καστανό'), ('blonde', 'Ξανθό'), ('red', 'Κόκκινο'), ('grey', 'Γκρι'), ('white', 'Άσπρο'), ('other', 'Άλλο'), ('unknown', 'Άγνωστο')], max_length=12, null=True, verbose_name='Χρώμα τριχών')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ClientConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_version', models.CharField(max_length=32)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='clients.client')),
            ],
        ),
    ]
