# Generated by Django 5.2.6 on 2026-02-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='receive_booking_email',
            field=models.BooleanField(default=True, help_text='Αποστολή email επιβεβαίωσης κράτησης', verbose_name='Λήψη Email κράτησης'),
        ),
        migrations.AddField(
            model_name='client',
            name='receive_booking_sms',
            field=models.BooleanField(default=True, help_text='Αποστολή SMS επιβεβαίωσης κράτησης', verbose_name='Λήψη SMS κράτησης'),
        ),
        migrations.AddField(
            model_name='client',
            name='receive_reminder_email',
            field=models.BooleanField(default=True, help_text='Αποστολή email υπενθύμισης 24 ώρες πριν το ραντεβού', verbose_name='Λήψη Email υπενθύμισης'),
        ),
        migrations.AddField(
            model_name='client',
            name='receive_reminder_sms',
            field=models.BooleanField(default=True, help_text='Αποστολή SMS υπενθύμισης 24 ώρες πριν το ραντεβού', verbose_name='Λήψη SMS υπενθύμισης'),
        ),
    ]
