# Generated by Django 5.2.6 on 2026-02-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_receive_booking_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='skin_type',
            field=models.CharField(blank=True, choices=[('light', 'Ανοιχτό'), ('medium', 'Μεσαίο'), ('medium_dark', 'Μεσαίο-Σκούρο'), ('dark', 'Σκούρο'), ('black', 'Μαύρο'), ('sensitive', 'Ευαίσθητο'), ('other', 'Άλλο')], max_length=15, null=True, verbose_name='Τύπος δέρματος'),
        ),
    ]
