# Generated by Django 5.2.6 on 2026-03-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_skin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='consent_form_signed',
            field=models.BooleanField(default=False, verbose_name='Φόρμα Συγκατάθεσης'),
        ),
        migrations.AddField(
            model_name='client',
            name='consent_form_url',
            field=models.URLField(blank=True, verbose_name='URL Φόρμας Συγκατάθεσης'),
        ),
    ]
