# Generated by Django 5.2.6 on 2026-01-28 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_appointment_created_at_appointment_created_by_and_more'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Template Name')),
                ('notification_type', models.CharField(choices=[('appointment_booked', 'Appointment Booked'), ('appointment_reminder', 'Appointment Reminder'), ('custom', 'Custom Message')], default='custom', max_length=30, verbose_name='Type')),
                ('sms_body', models.TextField(blank=True, help_text='Available variables: {client_name}, {date}, {time}, {service}, {staff}', verbose_name='SMS Body')),
                ('email_subject', models.CharField(blank=True, max_length=200, verbose_name='Email Subject')),
                ('email_body', models.TextField(blank=True, help_text='Available variables: {client_name}, {date}, {time}, {service}, {staff}', verbose_name='Email Body')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10, verbose_name='Channel')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered')], default='pending', max_length=20, verbose_name='Status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('external_id', models.CharField(blank=True, help_text='Twilio Message SID or Email Message ID', max_length=100, verbose_name='External ID')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='appointments.appointment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clients.client')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='notificatio_client__8364a2_idx'), models.Index(fields=['status', '-created_at'], name='notificatio_status_361e70_idx'), models.Index(fields=['appointment'], name='notificatio_appoint_acfff2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('24h_reminder', '24 Hour Reminder'), ('2h_reminder', '2 Hour Reminder'), ('followup', 'Follow-up')], max_length=30, verbose_name='Type')),
                ('send_sms', models.BooleanField(default=True, verbose_name='Send SMS')),
                ('send_email', models.BooleanField(default=True, verbose_name='Send Email')),
                ('scheduled_for', models.DateTimeField(verbose_name='Scheduled For')),
                ('sent', models.BooleanField(default=False, verbose_name='Sent')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('celery_task_id', models.CharField(blank=True, help_text='ID of the scheduled Celery task', max_length=100, verbose_name='Celery Task ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_notifications', to='appointments.appointment')),
            ],
            options={
                'verbose_name': 'Scheduled Notification',
                'verbose_name_plural': 'Scheduled Notifications',
                'ordering': ['scheduled_for'],
                'indexes': [models.Index(fields=['scheduled_for', 'sent'], name='notificatio_schedul_1f6919_idx'), models.Index(fields=['appointment'], name='notificatio_appoint_100b64_idx')],
            },
        ),
    ]
