# Generated by Django 5.2.6 on 2025-10-01 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('clients', '0001_initial'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[('booked', 'Κλεισμένο'), ('completed', 'Ολοκληρώθηκε'), ('no_show', 'Δεν προσήλθε'), ('cancelled', 'Ακυρώθηκε')], default='booked', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clients.client')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='resources.machine')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resources.room')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.service')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start'],
                'indexes': [models.Index(fields=['start'], name='appointment_start_3ae143_idx'), models.Index(fields=['room', 'start'], name='appointment_room_id_85c762_idx'), models.Index(fields=['staff', 'start'], name='appointment_staff_i_cad894_idx')],
            },
        ),
    ]
